### PR TITLE
Update log4j to 2.16.0

### PR DESCRIPTION
**Pull request by rahulsom**
This is in line with apache's new guidance on log4j-core

### CODE REVIEW

**Comment by BogdanLivadariu** [comment]
thanks for the bump @rahulsom  but i've already bumped it to 2.17.0 as part of my jdk-11 migration
https://github.com/web-innovate/bootstraped-multi-test-results-report/pull/96/commits/7659eaeb3fe4c40a60816ac82892b988aa6221c8

**Comment by rahulsom** [comment]
Thanks @BogdanLivadariu! What's the ETA on a release with the latest version? Once you have that, you might want to comment on https://issues.jenkins.io/browse/JENKINS-67353

**Comment by BogdanLivadariu** [comment]
I've just pushed out the 2.2.0 version, it should reach the plugin update page soon

**Comment by BogdanLivadariu** [comment]
@rahulsom  looks like it will take some more time, I'm unable to access my old account I was using to deploy the plugin to jenkins, so I'm waiting for : https://github.com/jenkins-infra/repository-permissions-updater/pull/2269  to land in, so I can push the `hpi` 

sorry for the delay ...

**Pull request closed without merging**
